name: Recently used languages metrics

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Executa semanalmente (opcional)

jobs:
  generate_recent_languages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate recently used languages SVG
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.recent.svg
          token: ${{ secrets.GITHUB_TOKEN }} # Podes usar GITHUB_TOKEN para pÃºblicos
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
