name: Metrics
on:
  # Executa a cada 24 horas
  schedule:
    - cron: "0 0 * * *"
  # Permite executar manualmente
  workflow_dispatch:
  # Executa ao fazer push para a branch principal
  push:
    branches:
      - "main"
      - "master"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # O seu nome de utilizador do GitHub
          user: manoper93

          # O seu token guardado nos segredos
          token: ${{ secrets.METRICS_TOKEN }}

          # Opções de configuração
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Plugin para o calendário isométrico (o gráfico que você quer)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Mostra o ano inteiro
